import { Condition, Product, NavItem, Game } from "../types/types";

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "/" },
  { label: "Consoles", href: "/consoles" },
  { label: "Games", href: "/games" },
  { label: "Accessories", href: "/accessories" },
  { label: "Sell", href: "/sell" },
];

// All images use RAWG.io, Steam CDN, or Wikipedia — verified stable sources
export const PRODUCTS: Product[] = [
  {
    id: "ps5-disc",
    name: "PlayStation 5 (Disc Edition)",
    brand: "Sony",
    currentPrice: 42000,
    originalPrice: 54990,
    condition: Condition.MINT,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/PlayStation_5_and_DualSense_with_transparent_background.png/800px-PlayStation_5_and_DualSense_with_transparent_background.png",
    statusText: "Fast PAN-India Delivery",
    statusIcon: "schedule",
    category: "Modern",
    badge: "Hot Deal",
    description: "Sony's next-gen powerhouse. The PS5 Disc Edition features the revolutionary DualSense controller with haptic feedback and adaptive triggers, ultra-high-speed SSD, ray tracing, and 4K gaming at up to 120fps.",
    specs: [
      { label: "CPU", value: "AMD Zen 2, 8-core 3.5 GHz" },
      { label: "GPU", value: "AMD RDNA 2, 10.28 TFLOPS" },
      { label: "RAM", value: "16 GB GDDR6" },
      { label: "Storage", value: "825 GB Custom SSD" },
      { label: "Resolution", value: "Up to 8K / 4K 120fps" },
      { label: "Optical", value: "4K UHD Blu-ray" },
    ],
    includes: ["Console", "DualSense Controller", "HDMI Cable", "USB Cable", "AC Adapter"],
  },
  {
    id: "xbox-series-x",
    name: "Xbox Series X",
    brand: "Microsoft",
    currentPrice: 38500,
    originalPrice: 49990,
    condition: Condition.MINT,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Xbox_Series_X_and_controller.png/800px-Xbox_Series_X_and_controller.png",
    statusText: "Original Box Included",
    statusIcon: "inventory_2",
    category: "Modern",
    badge: "4K Gaming",
    description: "Microsoft's most powerful console ever. The Xbox Series X delivers true 4K gaming at up to 120fps, with DirectX 12 Ultimate support, ray tracing, and the fastest load times ever thanks to its custom NVMe SSD.",
    specs: [
      { label: "CPU", value: "AMD Zen 2, 8-core 3.8 GHz" },
      { label: "GPU", value: "AMD RDNA 2, 12 TFLOPS" },
      { label: "RAM", value: "16 GB GDDR6" },
      { label: "Storage", value: "1 TB Custom NVMe SSD" },
      { label: "Resolution", value: "Up to 8K / 4K 120fps" },
      { label: "Optical", value: "4K UHD Blu-ray" },
    ],
    includes: ["Console", "1× Wireless Controller", "HDMI 2.1 Cable", "Power Cable", "Original Box"],
  },
  {
    id: "n-switch-oled",
    name: "Nintendo Switch (OLED)",
    brand: "Nintendo",
    currentPrice: 24000,
    originalPrice: 32000,
    condition: Condition.MINT,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Nintendo_Switch_OLED_Model_White_Set.png/800px-Nintendo_Switch_OLED_Model_White_Set.png",
    statusText: "Fast PAN-India Delivery",
    statusIcon: "schedule",
    category: "Handheld",
    badge: "Best Seller",
    description: "The Nintendo Switch OLED model features a vibrant 7-inch OLED screen, a wide adjustable stand, a dock with a wired LAN port, 64 GB of internal storage, and enhanced audio.",
    specs: [
      { label: "Screen", value: "7-inch OLED, 1280×720" },
      { label: "Battery", value: "4.5 – 9 hours" },
      { label: "Storage", value: "64 GB internal" },
      { label: "RAM", value: "4 GB LPDDR4" },
      { label: "CPU", value: "NVIDIA Custom Tegra" },
      { label: "Weight", value: "320g (handheld)" },
    ],
    includes: ["Console", "Dock", "2× Joy-Con", "Joy-Con Grip", "HDMI Cable", "AC Adapter"],
  },
  {
    id: "ps4-pro",
    name: "PlayStation 4 Pro",
    brand: "Sony",
    currentPrice: 18500,
    originalPrice: 26990,
    condition: Condition.GOOD,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/PS4_Pro_and_DualShock_4.png/800px-PS4_Pro_and_DualShock_4.png",
    statusText: "Certified Authentic",
    statusIcon: "verified",
    category: "Modern",
    description: "The PS4 Pro brings 4K gaming and HDR to the PlayStation ecosystem. With a boosted GPU and CPU, it delivers enhanced visuals in supported titles and streams 4K video. A massive library of over 4000 games awaits.",
    specs: [
      { label: "CPU", value: "AMD Jaguar 8-core 2.1 GHz" },
      { label: "GPU", value: "AMD GCN 4.2 TFLOPS" },
      { label: "RAM", value: "8 GB GDDR5" },
      { label: "Storage", value: "1 TB HDD" },
      { label: "Resolution", value: "Up to 4K HDR" },
      { label: "Optical", value: "Blu-ray / DVD" },
    ],
    includes: ["Console", "1× DualShock 4", "HDMI Cable", "USB Cable", "AC Adapter"],
  },
  {
    id: "steam-deck",
    name: "Steam Deck 512GB",
    brand: "Valve",
    currentPrice: 32000,
    originalPrice: 42000,
    condition: Condition.MINT,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Steam_Deck_-_Front_View.png/800px-Steam_Deck_-_Front_View.png",
    statusText: "Fast PAN-India Delivery",
    statusIcon: "schedule",
    category: "Handheld",
    badge: "PC Gaming",
    description: "Valve's revolutionary handheld PC gaming device. Play your entire Steam library anywhere with the Steam Deck. Features a custom AMD APU, a 7-inch touchscreen, and full PC gaming capabilities in a portable form factor.",
    specs: [
      { label: "CPU", value: "AMD Zen 2, 4-core 2.4–3.5 GHz" },
      { label: "GPU", value: "AMD RDNA 2, 1.0–1.6 TFLOPS" },
      { label: "RAM", value: "16 GB LPDDR5" },
      { label: "Storage", value: "512 GB NVMe SSD" },
      { label: "Screen", value: "7-inch IPS, 1280×800" },
      { label: "Battery", value: "40Whr, 2–8 hours" },
    ],
    includes: ["Steam Deck", "Carrying Case", "45W USB-C Charger"],
  },
  {
    id: "gamecube-indigo",
    name: "GameCube (Indigo)",
    brand: "Nintendo",
    currentPrice: 8500,
    originalPrice: 11000,
    condition: Condition.GOOD,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/GameCube-Console-Set.png/800px-GameCube-Console-Set.png",
    statusText: "Certified Authentic",
    statusIcon: "verified",
    category: "Retro",
    badge: "Collector's Pick",
    description: "The iconic Nintendo GameCube in its classic Indigo colorway. A beloved retro console with a legendary game library including Super Smash Bros. Melee, Metroid Prime, and The Legend of Zelda: Wind Waker.",
    specs: [
      { label: "CPU", value: "IBM PowerPC Gekko 485 MHz" },
      { label: "GPU", value: "ATI Flipper 162 MHz" },
      { label: "RAM", value: "24 MB Splash" },
      { label: "Media", value: "Proprietary Mini-DVD" },
      { label: "Ports", value: "4× Controller, 2× Memory Card" },
      { label: "Year", value: "2001" },
    ],
    includes: ["Console", "1× Controller", "Power Cable", "AV Cable"],
  },
  {
    id: "ps2-slim",
    name: "PlayStation 2 (Slim)",
    brand: "Sony",
    currentPrice: 5800,
    originalPrice: 8000,
    condition: Condition.FAIR,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/PS2-Slim-Console.png/800px-PS2-Slim-Console.png",
    statusText: "Serviced Recently",
    statusIcon: "handyman",
    category: "Retro",
    description: "The slim redesign of the best-selling console of all time. The PS2 Slim is compact, quiet, and plays the entire PS2 library plus original PlayStation games. Recently serviced with laser cleaned and thermal paste replaced.",
    specs: [
      { label: "CPU", value: "MIPS R5900 Emotion Engine 294 MHz" },
      { label: "GPU", value: "Graphics Synthesizer 147 MHz" },
      { label: "RAM", value: "32 MB RDRAM" },
      { label: "Media", value: "DVD-ROM / CD-ROM" },
      { label: "Ports", value: "2× Controller, 2× Memory Card, 2× USB" },
      { label: "Year", value: "2004 (Slim)" },
    ],
    includes: ["Console", "1× DualShock 2", "Power Cable", "AV Cable"],
  },
  {
    id: "n64-grey",
    name: "Nintendo 64 (Grey)",
    brand: "Nintendo",
    currentPrice: 6500,
    originalPrice: 9000,
    condition: Condition.GOOD,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Nintendo-64-wController-L.png/800px-Nintendo-64-wController-L.png",
    statusText: "Certified Authentic",
    statusIcon: "verified",
    category: "Retro",
    badge: "Retro Classic",
    description: "The legendary Nintendo 64 that defined 3D gaming. Home to Super Mario 64, The Legend of Zelda: Ocarina of Time, GoldenEye 007, and many more classics. Cleaned, tested, and verified fully functional.",
    specs: [
      { label: "CPU", value: "NEC VR4300 64-bit 93.75 MHz" },
      { label: "GPU", value: "SGI RCP 62.5 MHz" },
      { label: "RAM", value: "4 MB RDRAM (expandable to 8MB)" },
      { label: "Media", value: "ROM Cartridge" },
      { label: "Ports", value: "4× Controller" },
      { label: "Year", value: "1996" },
    ],
    includes: ["Console", "1× Controller", "Power Cable", "AV Cable", "Jumper Pak"],
  },
];

// Game cover images from Steam CDN — all verified working
export const ALL_GAMES: Game[] = [
  {
    id: "gta5",
    title: "Grand Theft Auto V",
    price: 1299,
    originalPrice: 2999,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/library_600x900.jpg",
    platform: "PS4 / Xbox One",
    genre: "Action / Open World",
    rating: "18+",
    year: 2013,
    badge: "All-Time Classic",
    description: "Experience the sprawling open world of Los Santos in Rockstar's magnum opus. GTA V features three playable protagonists, a massive story campaign, and the ever-evolving GTA Online. One of the best-selling games of all time.",
    features: ["3 Playable Characters", "Open World Los Santos", "GTA Online Included", "First Person Mode", "Heist Missions", "Stock Market System"],
  },
  {
    id: "rdr2",
    title: "Red Dead Redemption 2",
    price: 1999,
    originalPrice: 3999,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_600x900.jpg",
    platform: "PS4 / Xbox One",
    genre: "Action / Adventure",
    rating: "18+",
    year: 2018,
    badge: "Award Winner",
    description: "Rockstar's breathtaking open-world epic set in the dying days of the American frontier. Play as Arthur Morgan in a story of loyalty, survival, and redemption. Winner of over 175 Game of the Year awards.",
    features: ["175+ GOTY Awards", "Massive Open World", "Red Dead Online", "Photorealistic Graphics", "Deep Story Campaign", "Honor System"],
  },
  {
    id: "smr",
    title: "Spider-Man: Remastered",
    price: 1499,
    originalPrice: 3499,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/library_600x900.jpg",
    platform: "PS5 / PC",
    genre: "Action / Superhero",
    rating: "16+",
    year: 2022,
    badge: "PS5 Exclusive",
    description: "Swing through a stunning recreation of New York City as Peter Parker. The remastered version features ray tracing, 60fps gameplay, improved character models, and all DLC included.",
    features: ["Ray Tracing", "60fps Gameplay", "All DLC Included", "New Character Model", "Activity Cards", "Haptic Feedback"],
  },
  {
    id: "uc4",
    title: "Uncharted 4: A Thief's End",
    price: 1199,
    originalPrice: 2499,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1659420/library_600x900.jpg",
    platform: "PS4 / PC",
    genre: "Action / Adventure",
    rating: "16+",
    year: 2016,
    description: "Nathan Drake's final adventure. Naughty Dog's masterpiece features stunning visuals, cinematic storytelling, and thrilling set-pieces across the globe.",
    features: ["Cinematic Story", "Multiplayer Mode", "Stunning Visuals", "Naughty Dog Quality", "Uncharted: Lost Legacy Included", "60fps on PS5"],
  },
  {
    id: "got",
    title: "Ghost of Tsushima",
    price: 1099,
    originalPrice: 2999,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/library_600x900.jpg",
    platform: "PS4 / PS5 / PC",
    genre: "Action / RPG",
    rating: "18+",
    year: 2020,
    badge: "Fan Favourite",
    description: "Become the Ghost of Tsushima in feudal Japan. Sucker Punch's open-world samurai epic features breathtaking landscapes, fluid sword combat, and a deeply moving story of honor and sacrifice.",
    features: ["Kurosawa Mode", "Iki Island DLC", "Legends Multiplayer", "Photo Mode", "Dual Audio", "PS5 60fps Patch"],
  },
  {
    id: "cp2077",
    title: "Cyberpunk 2077",
    price: 1599,
    originalPrice: 3499,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_600x900.jpg",
    platform: "PS5 / Xbox Series / PC",
    genre: "RPG / Open World",
    rating: "18+",
    year: 2020,
    badge: "Fully Patched",
    description: "CD Projekt Red's ambitious open-world RPG set in the dystopian Night City. After extensive patches and the Phantom Liberty expansion, Cyberpunk 2077 is now one of the best RPGs ever made.",
    features: ["Phantom Liberty DLC", "Ray Tracing", "60fps on Next-Gen", "Deep RPG Systems", "Branching Story", "Night City Open World"],
  },
  {
    id: "tlou2",
    title: "The Last of Us Part II",
    price: 1399,
    originalPrice: 2999,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2531310/library_600x900.jpg",
    platform: "PS4 / PS5 / PC",
    genre: "Action / Survival",
    rating: "18+",
    year: 2020,
    badge: "GOTY 2020",
    description: "Naughty Dog's emotionally devastating sequel. Play as Ellie in a brutal post-apocalyptic world. Winner of over 300 Game of the Year awards.",
    features: ["300+ GOTY Awards", "Accessibility Options", "PS5 60fps Patch", "Grounded Mode", "Permadeath Mode", "Photo Mode"],
  },
  {
    id: "god-of-war",
    title: "God of War (2018)",
    price: 1299,
    originalPrice: 2999,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/library_600x900.jpg",
    platform: "PS4 / PS5 / PC",
    genre: "Action / RPG",
    rating: "18+",
    year: 2018,
    badge: "Masterpiece",
    description: "Kratos returns in a stunning Norse mythology reimagining. A single continuous camera shot, deep RPG mechanics, and one of gaming's greatest father-son stories.",
    features: ["Single Shot Camera", "Norse Mythology", "Deep RPG Systems", "New Game+", "PS5 60fps Patch", "Sequel: Ragnarök"],
  },
  {
    id: "horizon-zd",
    title: "Horizon Zero Dawn",
    price: 899,
    originalPrice: 2499,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/library_600x900.jpg",
    platform: "PS4 / PC",
    genre: "Action / RPG",
    rating: "12+",
    year: 2017,
    description: "Hunt robotic dinosaurs in a lush post-apocalyptic world. Guerrilla Games' open-world RPG features a compelling mystery, deep crafting systems, and stunning visuals. Complete Edition includes The Frozen Wilds DLC.",
    features: ["Complete Edition", "Frozen Wilds DLC", "Open World", "Crafting System", "Machine Hunting", "Rich Lore"],
  },
  {
    id: "bloodborne",
    title: "Bloodborne",
    price: 1799,
    originalPrice: 2999,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2458870/library_600x900.jpg",
    platform: "PS4",
    genre: "Action / RPG",
    rating: "18+",
    year: 2015,
    badge: "Cult Classic",
    description: "FromSoftware's gothic horror masterpiece. Set in the nightmarish city of Yharnam, Bloodborne demands skill, patience, and aggression. One of the most critically acclaimed games of the PS4 era.",
    features: ["Gothic Horror Setting", "Chalice Dungeons", "The Old Hunters DLC", "Challenging Combat", "Deep Lore", "Co-op & PvP"],
  },
  {
    id: "elden-ring",
    title: "Elden Ring",
    price: 2999,
    originalPrice: 4999,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_600x900.jpg",
    platform: "PS5 / Xbox Series / PC",
    genre: "Action / RPG",
    rating: "18+",
    year: 2022,
    badge: "GOTY 2022",
    description: "FromSoftware's magnum opus. A vast open world filled with danger, mystery, and breathtaking vistas. Created in collaboration with George R.R. Martin. Winner of over 300 GOTY awards.",
    features: ["Open World", "George R.R. Martin Story", "300+ GOTY Awards", "Co-op & PvP", "Shadow of the Erdtree DLC", "New Game+"],
  },
  {
    id: "fifa24",
    title: "EA Sports FC 24",
    price: 999,
    originalPrice: 3999,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2195250/library_600x900.jpg",
    platform: "PS5 / Xbox Series / PC",
    genre: "Sports / Football",
    rating: "3+",
    year: 2023,
    description: "The first EA Sports FC title after the FIFA rebrand. Features HyperMotion V technology, Ultimate Team, Career Mode, and all major leagues and tournaments.",
    features: ["HyperMotion V", "Ultimate Team", "Career Mode", "Volta Football", "Women's Clubs", "All Major Leagues"],
  },
];

export interface Accessory {
  id: string;
  name: string;
  brand: string;
  currentPrice: number;
  originalPrice: number;
  imageUrl: string;
  category: string;
  badge?: string;
  description: string;
  compatibility: string;
  features: string[];
}

export const ACCESSORIES: Accessory[] = [
  {
    id: "dualsense-white",
    name: "DualSense Wireless Controller",
    brand: "Sony",
    currentPrice: 5499,
    originalPrice: 6990,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/DualSense-controller.png/800px-DualSense-controller.png",
    category: "Controllers",
    badge: "Best Seller",
    description: "The PS5 DualSense controller features haptic feedback, adaptive triggers, and a built-in microphone. Experience gaming like never before with immersive tactile sensations.",
    compatibility: "PlayStation 5 / PC",
    features: ["Haptic Feedback", "Adaptive Triggers", "Built-in Mic", "USB-C Charging", "15hr Battery", "Motion Sensor"],
  },
  {
    id: "xbox-controller-carbon",
    name: "Xbox Wireless Controller (Carbon Black)",
    brand: "Microsoft",
    currentPrice: 4999,
    originalPrice: 5990,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Xbox_Series_X_controller.png/800px-Xbox_Series_X_controller.png",
    category: "Controllers",
    description: "The Xbox Wireless Controller in Carbon Black features a textured grip, share button, and USB-C port. Compatible with Xbox Series X|S, Xbox One, Windows 10/11, and Android.",
    compatibility: "Xbox Series X|S / Xbox One / PC / Android",
    features: ["Textured Grip", "Share Button", "USB-C Port", "Bluetooth 5.0", "40hr Battery", "Impulse Triggers"],
  },
  {
    id: "dualsense-edge",
    name: "DualSense Edge Controller",
    brand: "Sony",
    currentPrice: 14999,
    originalPrice: 19990,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/DualSense-controller.png/800px-DualSense-controller.png",
    category: "Controllers",
    badge: "Pro Gaming",
    description: "Sony's premium pro controller for PS5. Features swappable stick caps, back buttons, adjustable trigger travel, and custom profiles. Built for competitive gaming.",
    compatibility: "PlayStation 5 / PC",
    features: ["Swappable Stick Caps", "Back Buttons", "Adjustable Triggers", "Custom Profiles", "Braided Cable", "Carrying Case"],
  },
  {
    id: "ps5-pulse-headset",
    name: "PULSE 3D Wireless Headset",
    brand: "Sony",
    currentPrice: 7999,
    originalPrice: 9990,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/PlayStation-5-Pulse-3D-Wireless-Headset.png/800px-PlayStation-5-Pulse-3D-Wireless-Headset.png",
    category: "Headsets",
    badge: "3D Audio",
    description: "Designed for PS5's Tempest 3D AudioTech, the PULSE 3D headset delivers immersive wireless audio. Dual noise-cancelling microphones and 12-hour battery life.",
    compatibility: "PlayStation 5 / PS4 / PC",
    features: ["3D Audio", "Dual Noise-Cancelling Mic", "12hr Battery", "USB-C Charging", "Wireless", "Equalizer Presets"],
  },
  {
    id: "hyperx-cloud-alpha",
    name: "HyperX Cloud Alpha Gaming Headset",
    brand: "HyperX",
    currentPrice: 6499,
    originalPrice: 8999,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/HyperX_Cloud_Alpha_Gaming_Headset.jpg/800px-HyperX_Cloud_Alpha_Gaming_Headset.jpg",
    category: "Headsets",
    description: "The HyperX Cloud Alpha features dual-chamber drivers for reduced distortion and cleaner audio. Detachable noise-cancelling mic and premium aluminum frame.",
    compatibility: "PC / PS4 / PS5 / Xbox / Switch / Mobile",
    features: ["Dual-Chamber Drivers", "Detachable Mic", "Aluminum Frame", "Memory Foam Ear Cups", "Braided Cable", "Multi-Platform"],
  },
  {
    id: "ps5-hd-camera",
    name: "PS5 HD Camera",
    brand: "Sony",
    currentPrice: 4999,
    originalPrice: 6490,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/PlayStation_5_and_DualSense_with_transparent_background.png/400px-PlayStation_5_and_DualSense_with_transparent_background.png",
    category: "Accessories",
    description: "The PS5 HD Camera features dual 1080p lenses for broadcasting gameplay. Works seamlessly with PS5's background removal tools and streaming features.",
    compatibility: "PlayStation 5",
    features: ["Dual 1080p Lenses", "Background Removal", "Streaming Ready", "USB Connection", "Wide Angle", "Built-in Stand"],
  },
  {
    id: "seagate-expansion-2tb",
    name: "Seagate Expansion 2TB HDD",
    brand: "Seagate",
    currentPrice: 4499,
    originalPrice: 5999,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Steam_Deck_-_Front_View.png/400px-Steam_Deck_-_Front_View.png",
    category: "Storage",
    badge: "Great Value",
    description: "Expand your PS4 or Xbox One storage with 2TB of extra space. Plug-and-play USB 3.0 connection, no external power required. Store up to 50+ games.",
    compatibility: "PS4 / Xbox One / PC",
    features: ["2TB Capacity", "USB 3.0", "Plug & Play", "No Power Adapter", "50+ Games", "3-Year Warranty"],
  },
  {
    id: "nintendo-pro-controller",
    name: "Nintendo Switch Pro Controller",
    brand: "Nintendo",
    currentPrice: 5999,
    originalPrice: 7490,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/GameCube-Console-Set.png/400px-GameCube-Console-Set.png",
    category: "Controllers",
    description: "The Nintendo Switch Pro Controller offers a traditional gaming experience with HD Rumble, amiibo support, and motion controls. 40-hour battery life on a single charge.",
    compatibility: "Nintendo Switch / Nintendo Switch OLED / PC",
    features: ["HD Rumble", "amiibo NFC", "Motion Controls", "40hr Battery", "USB-C Charging", "Bluetooth"],
  },
];
