import { Condition, Product, NavItem, Game } from "../types/types";

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "/" },
  { label: "Consoles", href: "/consoles" },
  { label: "Games", href: "/games" },
  { label: "Accessories", href: "/accessories" },
  { label: "Sell", href: "/sell" },
];

export const PRODUCTS: Product[] = [
  {
    id: "n-switch-oled",
    name: "Nintendo Switch (OLED)",
    brand: "Nintendo",
    currentPrice: 24000,
    originalPrice: 32000,
    condition: Condition.MINT,
    imageUrl: "https://assets.nintendo.com/image/upload/f_auto/q_auto/dpr_2.0/c_scale,w_400/ncom/en_US/switch/site-design-update/hardware/switch/nintendo-switch-oled-model-white-set/gallery/image01",
    statusText: "Fast PAN-India Delivery",
    statusIcon: "schedule",
    category: "Handheld",
    badge: "Best Seller",
    description: "The Nintendo Switch OLED model features a vibrant 7-inch OLED screen, a wide adjustable stand, a dock with a wired LAN port, 64 GB of internal storage, and enhanced audio. Play at home or on the go in stunning OLED clarity.",
    specs: [
      { label: "Screen", value: "7-inch OLED, 1280×720" },
      { label: "Battery", value: "4.5 – 9 hours" },
      { label: "Storage", value: "64 GB internal" },
      { label: "RAM", value: "4 GB LPDDR4" },
      { label: "CPU", value: "NVIDIA Custom Tegra" },
      { label: "Weight", value: "320g (handheld)" },
    ],
    includes: ["Console", "Dock", "2× Joy-Con", "Joy-Con Grip", "HDMI Cable", "AC Adapter"],
  },
  {
    id: "ps5-disc",
    name: "PlayStation 5 (Disc Edition)",
    brand: "Sony",
    currentPrice: 42000,
    originalPrice: 54990,
    condition: Condition.MINT,
    imageUrl: "https://gmedia.playstation.com/is/image/SIEPDC/ps5-product-thumbnail-01-en-14sep21",
    statusText: "Fast PAN-India Delivery",
    statusIcon: "schedule",
    category: "Modern",
    badge: "Hot Deal",
    description: "Sony's next-gen powerhouse. The PS5 Disc Edition features the revolutionary DualSense controller with haptic feedback and adaptive triggers, ultra-high-speed SSD, ray tracing, and 4K gaming at up to 120fps.",
    specs: [
      { label: "CPU", value: "AMD Zen 2, 8-core 3.5 GHz" },
      { label: "GPU", value: "AMD RDNA 2, 10.28 TFLOPS" },
      { label: "RAM", value: "16 GB GDDR6" },
      { label: "Storage", value: "825 GB Custom SSD" },
      { label: "Resolution", value: "Up to 8K / 4K 120fps" },
      { label: "Optical", value: "4K UHD Blu-ray" },
    ],
    includes: ["Console", "DualSense Controller", "HDMI Cable", "USB Cable", "AC Adapter"],
  },
  {
    id: "xbox-series-x",
    name: "Xbox Series X",
    brand: "Microsoft",
    currentPrice: 38500,
    originalPrice: 49990,
    condition: Condition.MINT,
    imageUrl: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4mRni?ver=a707",
    statusText: "Original Box Included",
    statusIcon: "inventory_2",
    category: "Modern",
    badge: "4K Gaming",
    description: "Microsoft's most powerful console ever. The Xbox Series X delivers true 4K gaming at up to 120fps, with DirectX 12 Ultimate support, ray tracing, and the fastest load times ever thanks to its custom NVMe SSD.",
    specs: [
      { label: "CPU", value: "AMD Zen 2, 8-core 3.8 GHz" },
      { label: "GPU", value: "AMD RDNA 2, 12 TFLOPS" },
      { label: "RAM", value: "16 GB GDDR6" },
      { label: "Storage", value: "1 TB Custom NVMe SSD" },
      { label: "Resolution", value: "Up to 8K / 4K 120fps" },
      { label: "Optical", value: "4K UHD Blu-ray" },
    ],
    includes: ["Console", "1× Wireless Controller", "HDMI 2.1 Cable", "Power Cable", "Original Box"],
  },
  {
    id: "ps4-pro",
    name: "PlayStation 4 Pro",
    brand: "Sony",
    currentPrice: 18500,
    originalPrice: 26990,
    condition: Condition.GOOD,
    imageUrl: "https://gmedia.playstation.com/is/image/SIEPDC/ps4-pro-product-thumbnail-01-en-14sep21",
    statusText: "Certified Authentic",
    statusIcon: "verified",
    category: "Modern",
    description: "The PS4 Pro brings 4K gaming and HDR to the PlayStation ecosystem. With a boosted GPU and CPU, it delivers enhanced visuals in supported titles and streams 4K video. A massive library of over 4000 games awaits.",
    specs: [
      { label: "CPU", value: "AMD Jaguar 8-core 2.1 GHz" },
      { label: "GPU", value: "AMD GCN 4.2 TFLOPS" },
      { label: "RAM", value: "8 GB GDDR5" },
      { label: "Storage", value: "1 TB HDD" },
      { label: "Resolution", value: "Up to 4K HDR" },
      { label: "Optical", value: "Blu-ray / DVD" },
    ],
    includes: ["Console", "1× DualShock 4", "HDMI Cable", "USB Cable", "AC Adapter"],
  },
  {
    id: "steam-deck",
    name: "Steam Deck 512GB",
    brand: "Valve",
    currentPrice: 32000,
    originalPrice: 42000,
    condition: Condition.MINT,
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1675200/header.jpg",
    statusText: "Fast PAN-India Delivery",
    statusIcon: "schedule",
    category: "Handheld",
    badge: "PC Gaming",
    description: "Valve's revolutionary handheld PC gaming device. Play your entire Steam library anywhere with the Steam Deck. Features a custom AMD APU, a 7-inch touchscreen, and full PC gaming capabilities in a portable form factor.",
    specs: [
      { label: "CPU", value: "AMD Zen 2, 4-core 2.4–3.5 GHz" },
      { label: "GPU", value: "AMD RDNA 2, 1.0–1.6 TFLOPS" },
      { label: "RAM", value: "16 GB LPDDR5" },
      { label: "Storage", value: "512 GB NVMe SSD" },
      { label: "Screen", value: "7-inch IPS, 1280×800" },
      { label: "Battery", value: "40Whr, 2–8 hours" },
    ],
    includes: ["Steam Deck", "Carrying Case", "45W USB-C Charger"],
  },
  {
    id: "gamecube-indigo",
    name: "GameCube (Indigo)",
    brand: "Nintendo",
    currentPrice: 8500,
    originalPrice: 11000,
    condition: Condition.GOOD,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/GameCube-Console-Set.png/800px-GameCube-Console-Set.png",
    statusText: "Certified Authentic",
    statusIcon: "verified",
    category: "Retro",
    badge: "Collector's Pick",
    description: "The iconic Nintendo GameCube in its classic Indigo colorway. A beloved retro console with a legendary game library including Super Smash Bros. Melee, Metroid Prime, and The Legend of Zelda: Wind Waker.",
    specs: [
      { label: "CPU", value: "IBM PowerPC Gekko 485 MHz" },
      { label: "GPU", value: "ATI Flipper 162 MHz" },
      { label: "RAM", value: "24 MB Splash" },
      { label: "Media", value: "Proprietary Mini-DVD" },
      { label: "Ports", value: "4× Controller, 2× Memory Card" },
      { label: "Year", value: "2001" },
    ],
    includes: ["Console", "1× Controller", "Power Cable", "AV Cable"],
  },
  {
    id: "ps2-slim",
    name: "PlayStation 2 (Slim)",
    brand: "Sony",
    currentPrice: 5800,
    originalPrice: 8000,
    condition: Condition.FAIR,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/PS2-Slim-Console.png/800px-PS2-Slim-Console.png",
    statusText: "Serviced Recently",
    statusIcon: "handyman",
    category: "Retro",
    description: "The slim redesign of the best-selling console of all time. The PS2 Slim is compact, quiet, and plays the entire PS2 library plus original PlayStation games. Recently serviced with laser cleaned and thermal paste replaced.",
    specs: [
      { label: "CPU", value: "MIPS R5900 Emotion Engine 294 MHz" },
      { label: "GPU", value: "Graphics Synthesizer 147 MHz" },
      { label: "RAM", value: "32 MB RDRAM" },
      { label: "Media", value: "DVD-ROM / CD-ROM" },
      { label: "Ports", value: "2× Controller, 2× Memory Card, 2× USB" },
      { label: "Year", value: "2004 (Slim)" },
    ],
    includes: ["Console", "1× DualShock 2", "Power Cable", "AV Cable"],
  },
  {
    id: "n64-grey",
    name: "Nintendo 64 (Grey)",
    brand: "Nintendo",
    currentPrice: 6500,
    originalPrice: 9000,
    condition: Condition.GOOD,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Nintendo-64-wController-L.png/800px-Nintendo-64-wController-L.png",
    statusText: "Certified Authentic",
    statusIcon: "verified",
    category: "Retro",
    badge: "Retro Classic",
    description: "The legendary Nintendo 64 that defined 3D gaming. Home to Super Mario 64, The Legend of Zelda: Ocarina of Time, GoldenEye 007, and many more classics. Cleaned, tested, and verified fully functional.",
    specs: [
      { label: "CPU", value: "NEC VR4300 64-bit 93.75 MHz" },
      { label: "GPU", value: "SGI RCP 62.5 MHz" },
      { label: "RAM", value: "4 MB RDRAM (expandable to 8MB)" },
      { label: "Media", value: "ROM Cartridge" },
      { label: "Ports", value: "4× Controller" },
      { label: "Year", value: "1996" },
    ],
    includes: ["Console", "1× Controller", "Power Cable", "AV Cable", "Jumper Pak"],
  },
];

export const ALL_GAMES: Game[] = [
  {
    id: "gta5",
    title: "Grand Theft Auto V",
    price: 1299,
    originalPrice: 2999,
    image: "/GTA5.png",
    platform: "PS4 / Xbox One",
    genre: "Action / Open World",
    rating: "18+",
    year: 2013,
    badge: "All-Time Classic",
    description: "Experience the sprawling open world of Los Santos in Rockstar's magnum opus. GTA V features three playable protagonists, a massive story campaign, and the ever-evolving GTA Online. One of the best-selling games of all time.",
    features: ["3 Playable Characters", "Open World Los Santos", "GTA Online Included", "First Person Mode", "Heist Missions", "Stock Market System"],
  },
  {
    id: "rdr2",
    title: "Red Dead Redemption 2",
    price: 1999,
    originalPrice: 3999,
    image: "/RDR2.png",
    platform: "PS4 / Xbox One",
    genre: "Action / Adventure",
    rating: "18+",
    year: 2018,
    badge: "Award Winner",
    description: "Rockstar's breathtaking open-world epic set in the dying days of the American frontier. Play as Arthur Morgan in a story of loyalty, survival, and redemption. Winner of over 175 Game of the Year awards.",
    features: ["175+ GOTY Awards", "Massive Open World", "Red Dead Online", "Photorealistic Graphics", "Deep Story Campaign", "Honor System"],
  },
  {
    id: "smr",
    title: "Spider-Man: Remastered",
    price: 1499,
    originalPrice: 3499,
    image: "/SMR.png",
    platform: "PS5",
    genre: "Action / Superhero",
    rating: "16+",
    year: 2022,
    badge: "PS5 Exclusive",
    description: "Swing through a stunning recreation of New York City as Peter Parker. The remastered version features ray tracing, 60fps gameplay, improved character models, and all DLC included.",
    features: ["Ray Tracing", "60fps Gameplay", "All DLC Included", "New Character Model", "Activity Cards", "Haptic Feedback"],
  },
  {
    id: "uc4",
    title: "Uncharted 4: A Thief's End",
    price: 1199,
    originalPrice: 2499,
    image: "/UC4.png",
    platform: "PS4",
    genre: "Action / Adventure",
    rating: "16+",
    year: 2016,
    description: "Nathan Drake's final adventure. Naughty Dog's masterpiece features stunning visuals, cinematic storytelling, and thrilling set-pieces across the globe.",
    features: ["Cinematic Story", "Multiplayer Mode", "Stunning Visuals", "Naughty Dog Quality", "Uncharted: Lost Legacy Included", "60fps on PS5"],
  },
  {
    id: "got",
    title: "Ghost of Tsushima",
    price: 1099,
    originalPrice: 2999,
    image: "/GoT.png",
    platform: "PS4 / PS5",
    genre: "Action / RPG",
    rating: "18+",
    year: 2020,
    badge: "Fan Favourite",
    description: "Become the Ghost of Tsushima in feudal Japan. Sucker Punch's open-world samurai epic features breathtaking landscapes, fluid sword combat, and a deeply moving story of honor and sacrifice.",
    features: ["Kurosawa Mode", "Iki Island DLC", "Legends Multiplayer", "Photo Mode", "Dual Audio", "PS5 60fps Patch"],
  },
  {
    id: "cp2077",
    title: "Cyberpunk 2077",
    price: 1599,
    originalPrice: 3499,
    image: "/CP.png",
    platform: "PS5 / Xbox Series",
    genre: "RPG / Open World",
    rating: "18+",
    year: 2020,
    badge: "Fully Patched",
    description: "CD Projekt Red's ambitious open-world RPG set in the dystopian Night City. After extensive patches and the Phantom Liberty expansion, Cyberpunk 2077 is now one of the best RPGs ever made.",
    features: ["Phantom Liberty DLC", "Ray Tracing", "60fps on Next-Gen", "Deep RPG Systems", "Branching Story", "Night City Open World"],
  },
  {
    id: "tlou2",
    title: "The Last of Us Part II",
    price: 1399,
    originalPrice: 2999,
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202010/0222/niMUubpU9y1PxNvYmDfb8QFD.png",
    platform: "PS4 / PS5",
    genre: "Action / Survival",
    rating: "18+",
    year: 2020,
    badge: "GOTY 2020",
    description: "Naughty Dog's emotionally devastating sequel. Play as Ellie in a brutal post-apocalyptic world. Winner of over 300 Game of the Year awards.",
    features: ["300+ GOTY Awards", "Accessibility Options", "PS5 60fps Patch", "Grounded Mode", "Permadeath Mode", "Photo Mode"],
  },
  {
    id: "god-of-war",
    title: "God of War (2018)",
    price: 1299,
    originalPrice: 2999,
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/eEczyEMDd2BLa3dtkGJVE9Id.png",
    platform: "PS4 / PS5",
    genre: "Action / RPG",
    rating: "18+",
    year: 2018,
    badge: "Masterpiece",
    description: "Kratos returns in a stunning Norse mythology reimagining. A single continuous camera shot, deep RPG mechanics, and one of gaming's greatest father-son stories.",
    features: ["Single Shot Camera", "Norse Mythology", "Deep RPG Systems", "New Game+", "PS5 60fps Patch", "Sequel: Ragnarök"],
  },
  {
    id: "horizon-zd",
    title: "Horizon Zero Dawn",
    price: 899,
    originalPrice: 2499,
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202008/1420/T3h9SiCMbFBsNDKoRcFrFkiB.png",
    platform: "PS4 / PC",
    genre: "Action / RPG",
    rating: "12+",
    year: 2017,
    description: "Hunt robotic dinosaurs in a lush post-apocalyptic world. Guerrilla Games' open-world RPG features a compelling mystery, deep crafting systems, and stunning visuals. Complete Edition includes The Frozen Wilds DLC.",
    features: ["Complete Edition", "Frozen Wilds DLC", "Open World", "Crafting System", "Machine Hunting", "Rich Lore"],
  },
  {
    id: "bloodborne",
    title: "Bloodborne",
    price: 1799,
    originalPrice: 2999,
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202010/0222/nBCFpFqbEP7K6fgOxGzBHXlr.png",
    platform: "PS4",
    genre: "Action / RPG",
    rating: "18+",
    year: 2015,
    badge: "Cult Classic",
    description: "FromSoftware's gothic horror masterpiece. Set in the nightmarish city of Yharnam, Bloodborne demands skill, patience, and aggression. One of the most critically acclaimed games of the PS4 era.",
    features: ["Gothic Horror Setting", "Chalice Dungeons", "The Old Hunters DLC", "Challenging Combat", "Deep Lore", "Co-op & PvP"],
  },
  {
    id: "fifa24",
    title: "EA Sports FC 24",
    price: 999,
    originalPrice: 3999,
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202307/2811/0607a2e3e1e3b1e3e1e3b1e3.png",
    platform: "PS5 / Xbox Series",
    genre: "Sports / Football",
    rating: "3+",
    year: 2023,
    description: "The first EA Sports FC title after the FIFA rebrand. Features HyperMotion V technology, Ultimate Team, Career Mode, and all major leagues and tournaments.",
    features: ["HyperMotion V", "Ultimate Team", "Career Mode", "Volta Football", "Women's Clubs", "All Major Leagues"],
  },
  {
    id: "mortal-kombat1",
    title: "Mortal Kombat 1",
    price: 2499,
    originalPrice: 4999,
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202306/1219/1c3f0b3b3b3b3b3b3b3b3b3b.png",
    platform: "PS5 / Xbox Series / Switch",
    genre: "Fighting",
    rating: "18+",
    year: 2023,
    badge: "New Arrival",
    description: "NetherRealm Studios reboots the MK universe with a brand new timeline. Features the Kameo Fighter system, stunning fatalities, and a deep story mode.",
    features: ["Kameo Fighter System", "Invasions Mode", "Story Mode", "Online Ranked", "Brutal Fatalities", "DLC Fighters"],
  },
];
